[package]
name = "app-std"
version = "0.1.0"
edition = "2024"

[dependencies]
secs-common.workspace = true
secs-ii.workspace = true
secs-runtime.workspace = true
secs-runtime-core.workspace = true
secs-runtime-std.workspace = true
secs-transport.workspace = true
env_logger.workspace = true
log.workspace = true

