[package]
name = "secs-runtime-web"
version = "0.1.0"
edition = "2024"

[lib]
# for wasm build
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.82"
log.workspace = true
secs-common.workspace = true
secs-ii.workspace = true
secs-runtime.workspace = true
secs-runtime-core.workspace = true
secs-transport.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.55"

[dependencies.web-sys]
version = "0.3.82"
features = [
    "console",
    "Window",
]
